repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.12
        args: [--line-length=100]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: .venv/bin/python -m pylint
        language: system
        args: [--errors-only]
        files: ^POMDPPlanners/.*\.py$
        exclude: ^POMDPPlanners/tests/.*$
        pass_filenames: true

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.391
    hooks:
      - id: pyright
        files: ^docs/examples/.*\.ipynb$
        args: [docs/examples/]
        exclude: ^type_hints\.py$

      - id: pyright
        name: pyright (POMDPPlanners)
        files: ^POMDPPlanners/.*\.py$
        args: [POMDPPlanners/]
