[mypy]
python_version = 3.9
ignore_missing_imports = True
follow_imports = skip
warn_unused_ignores = True
warn_redundant_casts = True
warn_no_return = False
warn_return_any = False
disable_error_code = import-untyped
exclude = ^(POMDPPlanners/core/|POMDPPlanners/environments/|POMDPPlanners/planners/|POMDPPlanners/simulations/|POMDPPlanners/tests/|POMDPPlanners/configs/|POMDPPlanners/utils/)

