# SPDX-License-Identifier: MIT

"""Calibration tests for the ANYmal navigation setup.

Calibration is the only fitted part of an otherwise analytic model, so these tests are mostly
round trips: synthesize a rollout from known tracking scales and demand they come back. A
calibration that silently returns 1.0 would not raise anywhere -- the model would simply believe
the base tracks perfectly, and its predicted goal would drift a little further from the observed
one every step.

The reset test is the one that catches a real hazard. IsaacLab auto-resets on timeout and resamples
the pose command with it, so a warm-up rollout of a few hundred steps *always* contains transitions
whose goal jumped metres. Fitting them would drag both scales toward nonsense.
"""

from typing import Any, Tuple

import numpy as np
import pytest

from POMDPPlanners.environments.isaac_lab_pomdp.isaac_generative_models import (
    NavigationIsaacModel,
    calibrate_command_tracking,
    calibrate_navigation_noise,
    navigation_state_schema,
)
from POMDPPlanners.environments.isaac_lab_pomdp.isaac_generative_models.isaac_anymal_navigation_setup import (  # noqa: E501  pylint: disable=line-too-long
    MINIMUM_NOISE_STD,
    AnymalNavigationLayout,
    build_anymal_navigation_model,
)
from POMDPPlanners.environments.isaac_lab_pomdp.isaac_generative_models.isaac_navigation_model import (  # noqa: E501  pylint: disable=line-too-long
    GoalRelativeTransition,
)

STEP_DT = 0.2
SCHEMA = navigation_state_schema()
LAYOUT = AnymalNavigationLayout(step_dt=STEP_DT)
PRESETS = [
    np.zeros(3),
    np.array([1.0, 0.0, 0.0]),
    np.array([0.0, 0.0, 1.0]),
    np.array([0.6, -0.4, 0.5]),
    np.array([-0.7, 0.3, -0.8]),
]


def _rollout(
    linear_scale: float,
    angular_scale: float,
    steps: int = 200,
    noise_std: float = 0.0,
    seed: int = 0,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """A warm-up rollout generated by a model with known tracking scales."""
    rng = np.random.default_rng(seed)
    transition = GoalRelativeTransition(
        step_dt=STEP_DT,
        linear_scale=linear_scale,
        angular_scale=angular_scale,
        velocity_noise_std=1e-9,
        position_noise_std=1e-9,
        heading_noise_std=1e-9,
    )
    driven = SCHEMA.indices_of(("base_lin_vel", "pose_command"))
    state = SCHEMA.pack(
        {
            "base_lin_vel": np.zeros(3),
            "projected_gravity": [0.0, 0.0, -1.0],
            "pose_command": [2.5, -1.5, 0.0, 0.4],
        }
    )
    states, actions, next_states = [], [], []
    for _ in range(steps):
        action = PRESETS[int(rng.integers(len(PRESETS)))]
        following = state.copy()
        following[driven] = transition.predict_next(state[driven], action)[0]
        if noise_std > 0.0:
            following[driven] += rng.normal(0.0, noise_std, size=driven.shape[0])
        states.append(state)
        actions.append(action)
        next_states.append(following)
        state = following
    return np.asarray(states), np.asarray(actions), np.asarray(next_states)


def _with_reset(
    rollout: Tuple[np.ndarray, np.ndarray, np.ndarray], row: int = 40
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """The same rollout with one transition replaced by an episode boundary."""
    states, actions, next_states = (array.copy() for array in rollout)
    goal = SCHEMA.slice_of("pose_command")
    next_states[row, goal] = [-2.9, 2.7, 0.0, -2.6]  # a freshly resampled command and heading
    return states, actions, next_states


# ── Round-trip calibration ──────────────────────────────────────────────


@pytest.mark.parametrize("linear_scale, angular_scale", [(1.0, 1.0), (0.8, 0.6), (0.45, 0.95)])
def test_calibration_recovers_the_tracking_scales_that_generated_the_rollout(
    linear_scale: float, angular_scale: float
) -> None:
    """A calibration that quietly returns 1.0 makes the model wrong in a way nothing raises about.

    Purpose: Validates that both tracking scales are recovered from a rollout that used them

    Given: A noise-free rollout generated at known linear and angular tracking scales
    When: The scales are calibrated back out of the observations and commands alone
    Then: Both come back to within a thousandth

    Test type: unit
    """
    states, actions, next_states = _rollout(linear_scale, angular_scale)
    recovered = calibrate_command_tracking(states, actions, next_states, STEP_DT, SCHEMA)
    assert recovered[0] == pytest.approx(linear_scale, abs=1e-3)
    assert recovered[1] == pytest.approx(angular_scale, abs=1e-3)


def test_calibration_uses_only_the_observation_and_the_command() -> None:
    """The claim that no privileged data is read is worth a test, not just a docstring.

    Purpose: Validates that calibration reads nothing outside the pose_command block

    Given: A rollout whose velocity and gravity blocks have been overwritten with garbage
    When: The tracking scales are calibrated
    Then: They are unchanged from the untouched rollout

    Test type: unit
    """
    states, actions, next_states = _rollout(0.8, 0.6)
    baseline = calibrate_command_tracking(states, actions, next_states, STEP_DT, SCHEMA)
    corrupted_states, corrupted_next = states.copy(), next_states.copy()
    for block in ("base_lin_vel", "projected_gravity"):
        corrupted_states[:, SCHEMA.slice_of(block)] = 99.0
        corrupted_next[:, SCHEMA.slice_of(block)] = -99.0
    recovered = calibrate_command_tracking(
        corrupted_states, actions, corrupted_next, STEP_DT, SCHEMA
    )
    assert recovered == pytest.approx(baseline, abs=1e-12)


def test_an_episode_reset_does_not_drag_the_calibrated_scales() -> None:
    """A 200-step warm-up spans several 40-step episodes, so this row is always present.

    Purpose: Validates that transitions spanning an episode reset are excluded from the fit

    Given: A rollout at known scales with one transition replaced by a resampled pose command
    When: The scales are calibrated over it
    Then: They still match the scales that generated the clean transitions

    Test type: unit
    """
    rollout = _rollout(0.8, 0.6)
    recovered = calibrate_command_tracking(*_with_reset(rollout), STEP_DT, SCHEMA)
    assert recovered[0] == pytest.approx(0.8, abs=1e-3)
    assert recovered[1] == pytest.approx(0.6, abs=1e-3)


def test_calibration_refuses_a_rollout_that_never_commands_a_move() -> None:
    """An unidentifiable fit must fail loudly rather than return a default that looks measured.

    Purpose: Validates the guard against a rollout of zero commands

    Given: A rollout in which every issued command is the zero action
    When: The tracking scales are calibrated
    Then: ValueError is raised

    Test type: unit
    """
    states, actions, next_states = _rollout(1.0, 1.0, steps=20)
    with pytest.raises(ValueError, match="unidentifiable"):
        calibrate_command_tracking(states, np.zeros_like(actions), next_states, STEP_DT, SCHEMA)


# ── Noise calibration ───────────────────────────────────────────────────


def test_noise_calibration_recovers_the_noise_injected_into_the_rollout() -> None:
    """A guessed process noise leaves the belief overconfident or diffuse for no stated reason.

    Purpose: Validates that the measured stds track the noise actually present

    Given: A rollout at known scales corrupted with a known per-entry noise
    When: The residual noise is measured against those scales
    Then: All three stds land near the injected level

    Test type: unit
    """
    rollout = _rollout(0.8, 0.6, steps=4000, noise_std=0.02, seed=3)
    measured = calibrate_navigation_noise(*rollout, STEP_DT, (0.8, 0.6), SCHEMA)
    for std in measured:
        assert std == pytest.approx(0.02, abs=6e-3)


def test_noise_calibration_floors_a_perfectly_clean_rollout() -> None:
    """A zero std makes the transition density degenerate and every particle weight but one -inf.

    Purpose: Validates the floor on a measured noise std

    Given: A noise-free rollout at the same scales used to measure it
    When: The residual noise is measured
    Then: Every std is at the configured minimum rather than zero

    Test type: unit
    """
    measured = calibrate_navigation_noise(*_rollout(0.8, 0.6), STEP_DT, (0.8, 0.6), SCHEMA)
    for std in measured:
        assert std == pytest.approx(MINIMUM_NOISE_STD)


# ── Assembly ────────────────────────────────────────────────────────────


def test_the_assembled_model_carries_the_calibrated_scales_and_the_task_schema() -> None:
    """The builder is where a calibration could be measured and then quietly not applied.

    Purpose: Validates that build_anymal_navigation_model wires its measurements into the model

    Given: A rollout generated at known tracking scales
    When: The model is assembled from it
    Then: Its transition carries those scales, its step matches the layout, and its state schema is
        the task's ten-wide observation group

    Test type: unit
    """
    model = build_anymal_navigation_model(
        None, _rollout(0.75, 0.55), PRESETS, discount_factor=0.99, layout=LAYOUT
    )
    assert model.goal_transition.linear_scale == pytest.approx(0.75, abs=1e-3)
    assert model.goal_transition.angular_scale == pytest.approx(0.55, abs=1e-3)
    assert model.goal_transition.step_dt == pytest.approx(STEP_DT)
    assert model.state_schema.names == ("base_lin_vel", "projected_gravity", "pose_command")
    assert model.state_schema.total_dim == 10
    assert isinstance(model, NavigationIsaacModel)


def test_the_builder_refuses_an_observation_that_is_not_the_shape_it_expects() -> None:
    """A changed observation group would not raise, it would shift every channel offset silently.

    Purpose: Validates the width check between the rollout and the task's implied schema

    Given: A rollout whose observations are wider than the task's policy group
    When: The model is assembled from it
    Then: RuntimeError is raised naming the mismatch

    Test type: unit
    """
    states, actions, next_states = _rollout(0.8, 0.6, steps=20)
    padded = (np.hstack([states, states[:, :1]]), actions, np.hstack([next_states, states[:, :1]]))
    with pytest.raises(RuntimeError, match="the group has changed"):
        build_anymal_navigation_model(None, padded, PRESETS, discount_factor=0.99, layout=LAYOUT)


def test_the_layout_reads_the_control_step_off_a_live_task() -> None:
    """Every predicted displacement is linear in the control step, so a guessed one scales them all.

    Purpose: Validates that the layout reads step_dt from the environment rather than assuming it

    Given: A stub task reporting a 0.2 s control step
    When: The layout is read from it
    Then: It carries that step

    Test type: unit
    """
    # pylint: disable-next=import-outside-toplevel
    from POMDPPlanners.environments.isaac_lab_pomdp.isaac_generative_models import (
        anymal_navigation_layout,
    )

    class _Unwrapped:
        step_dt = 0.2

    class _Env:
        unwrapped: Any = _Unwrapped()

    assert anymal_navigation_layout(_Env()).step_dt == pytest.approx(0.2)
